### PR TITLE
Replace current about dialog with settings page

### PR DESCRIPTION
**Pull request by grochocki**
### Replace current about dialog with settings page

**Feature Pitch Link:** Microsoft/calculator#596

### CODE REVIEW

**Comment by Chips1234** [comment]
@grochocki I played around with it and I have a few questions: 

1. Since the footer is constructed in MainPage, is there any idea on how to implement it code wise. We can’t do something like:  `m_graphingCalculator->Visibility = BooleanToVisibilityConverter::Convert(isGraphingCalcViewMode);` since we don’t have a Boolean (It is initialized in NavCategory). 
2. How do we change the app theme in the app? 

Thanks!

**Comment by grochocki** [comment]
I'll defer to @sanderl on implementation details.

**Comment by Chips1234** [comment]
Alright thanks

________________________________

**Review by Chips1234 — DISMISSED** [review]
It's nice

**Comment by sanderl** [comment]
> @grochocki I played around with it and I have a few questions:
> 
> 1. Since the footer is constructed in MainPage, is there any idea on how to implement it code wise. We can’t do something like:  `m_graphingCalculator->Visibility = BooleanToVisibilityConverter::Convert(isGraphingCalcViewMode);` since we don’t have a Boolean (It is initialized in NavCategory).
> 2. How do we change the app theme in the app?
> 
> Thanks!

Hi @Chips1234, I'm not sure I understand your first question. Are you asking how we would implement the entry point to Settings page in the Nav View?

For your second question, you can change the app them using the Application.RequestedTheme property (https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.application.requestedtheme?view=winrt-19041) during app initialization.

**Comment by Chips1234** [comment]
> Hi @Chips1234, I'm not sure I understand your first question. Are you asking how we would implement the entry point to Settings page in the Nav View?

Thanks @sanderl! Yes, I that is what I mean in the first question

**Comment by sanderl** [comment]
> > Hi @Chips1234, I'm not sure I understand your first question. Are you asking how we would implement the entry point to Settings page in the Nav View?
> 
> Thanks @sanderl! Yes, I that is what I mean in the first question

@Chips1234, I think we would likely remove the Flyout part of the NavigationView.PaneFooter in MainPage.xaml and have the NavigationViewItem changed to Settings (from About) and then have it navigate to a new Settings page in a similar way that we navigate to the other pages. Does that help answer your question?

**Comment by Chips1234** [comment]
Alright. I’ll try it. Thanks

________________________________

**Comment by Chips1234** [comment]
@grochocki I think there should be a hyperlink button that leads to personalization settings (with a URI Launcher)

**Comment by grochocki** [comment]
> I think there should be a hyperlink button that leads to personalization settings (with a URI Launcher)

Something like this?

image

**Comment by Chips1234** [comment]
> > I think there should be a hyperlink button that leads to personalization settings (with a URI Launcher)
> 
> Something like this?
> 
> image

Yes, like that

**Comment by Chips1234** [comment]
@sanderl So we should have a holder with a border?
```xaml
<Border x:Name="SettingsHolder">
<!-- PLACEHOLDER!!!! This is where the converter goes when it is delay loaded -->
</Border>
```

```cpp

if (!SettingsHolder)
    {
        m_settings->Name = L"Settings";
        SettingsHolder->Child = m_settings;
    }
```

**Comment by sanderl** [comment]
> @sanderl So we should have a holder with a border?
>

@Chips1234, yes I would create a SettingsHolder in MainPage.xaml. For the code behind, you will want to mostly look at how Unit Converter or Graphing mode is navigated to, so you'll want to add an EnsureSettings(), add Settings as a Mode and a NavCategory, update OnAppPropertyChanged() to have the Settings page, etc.

It looks like you're on the right track with the code snippets you provided.

**Comment by Chips1234** [comment]
@senderl Sorry to bug you again, but since the footer is constructed in MainPage, how do I return ViewMode::Settings?

**Comment by sanderl** [comment]
> @senderl Sorry to bug you again, but since the footer is constructed in MainPage, how do I return ViewMode::Settings?

@Chips1234, I haven't tried this, but I'm wondering if you can updated the ItemClicked method in the NavViewItem

 <muxc:NavigationViewList x:Name="NavFooter"
                                             Width="{StaticResource SplitViewOpenPaneLength}"
                                             IsItemClickEnabled="True"
                                             **ItemClick="OnAboutButtonClick"**
                                             x:Load="False">

This used to launch the flyout, but I think you can just navigate to the Settings page instead.

Does that help?

**Comment by Chips1234** [comment]
@sanderl Yes, I have. Now I'm trying:
```c++
void MainPage::OnAboutButtonClick(Object ^ sender, ItemClickEventArgs ^ e)
{
    ViewMode::Settings;
    EnsureSettings();
}
```
But it does not work

**Comment by sanderl** [comment]
@Chips1234 can you try using for Itemclicked. You'll need to add the Settings Mode and possibly NavigationCategory.

void MainPage::OnNavSelectionChanged(_In_ Object ^ sender, _In_ MUXC::NavigationViewSelectionChangedEventArgs ^ e)
{
    auto item = dynamic_cast<MUXC::NavigationViewItem ^>(e->SelectedItemContainer);
    if (item != nullptr)
    {
        auto selectedItem = static_cast<NavCategory ^>(item->DataContext);
        Model->Mode = selectedItem->Mode;
    }
}


I think when the Model->Mode updates then OnAppPropertyChanged() is called. You may need to debug the navigation from one of the other pages to figure out the exact path that Settings will need to follow.

**Comment by Chips1234** [comment]
> @Chips1234 can you try using for Itemclicked. You'll need to add the Settings Mode and possibly NavigationCategory.
> 
> 
> 
> void MainPage::OnNavSelectionChanged(_In_ Object ^ sender, _In_ MUXC::NavigationViewSelectionChangedEventArgs ^ e)
> 
> {
> 
>     auto item = dynamic_cast<MUXC::NavigationViewItem ^>(e->SelectedItemContainer);
> 
>     if (item != nullptr)
> 
>     {
> 
>         auto selectedItem = static_cast<NavCategory ^>(item->DataContext);
> 
>         Model->Mode = selectedItem->Mode;
> 
>     }
> 
> }
> 
> 
> 
> 
> 
> I think when the Model->Mode updates then OnAppPropertyChanged() is called. You may need to debug the navigation from one of the other pages to figure out the exact path that Settings will need to follow.

Hmm... Alright. Thanks

**Review by volkcor — APPROVED** [review]
Looks good!

**Pull request merged**
